## YAML Template.
---
#driverDB: com.mysql.jdbc.Driver
#urlDB: jdbc:mysql://db4free.net:3307/clasesdaw?useSSL=false
driverDB: org.hsqldb.jdbc.JDBCDriver
urlDB: jdbc:hsqldb:mem:biblioteca
userDB: oscarnovillo
passDB: c557ef

